### ISSUE TITLE
Hapi >= 8 Listed as Peer Dependency But Not Used

### ISSUE THREAD

**Issue by DavidTPate** [hapijs/scooter#35]
I see that [here](https://github.com/hapijs/scooter/blob/3e18271cd697689b1d3829b6bc9b4e09e73b1490/package.json#L21) Hapi is listed as a peer-dependency but not actually used anywhere within the code. Looking through the commit history it appears to be this way so that it is run on a compatible Hapi version.

This doesn't seem like the correct usage of `peerDependencies` to me and it is also preventing me from locking down my dependencies (and sub-dependencies) via `shrinkwrap` without including `hapi` as a dependency in my module.

In my particular case I have a shared module with common plugins for my Hapi servers. These plugins are not dependent upon Hapi (similar to `scooter`) but are meant to be used with it.

**Comment by Marsup** [comment]
You have to report your compatibility level at some point, I don't see any other way.

**Comment by DavidTPate** [comment]
Yeah, I can't think of any good way to do this "programatically" than what's currently being done. Currently it is an enforcement as opposed to just a report.

The only other way that I could see it being done is a simple note in the Readme, but that could lead to some weird cases where people don't read it and try to use it with an old version of Hapi. Aside from my issue with `shrinkwrap` it also means that this module isn't usable outside of Hapi (not really a good argument, I admit just pointing it out).

I'd love for someone to just have some magic solution to this, but I don't believe one exists.

**Comment by Marsup** [comment]
I don't understand your issue here, hapi >= 8.x.x is very lax, are you working with older versions than that ?

**Comment by danielb2** [comment]
I'll have a look at this too in a bit, but on vacation and a bit distracted atm ;)

**Comment by DavidTPate** [comment]
Reading over my initial post it does seem a bit rambling. Let me set this up a little bit more to explain what is going on for me.

* I'm not using an old version of `hapi`.
* I'm trying to use `scooter` in a private Node Module separate from my Hapi server (the module contains common code & configuration for all of my servers running Hapi).

In terms of dependencies because of the `peerDependency` requirement I have to have the following for my dependencies for my projects:

**Node module with `scooter` in it**
* `scooter`
* `hapi`
* other modules

**Hapi Servers**
* private module with scooter and other common things in it
  * `scooter`
  * `hapi`
* `hapi`
* other modules

What I would like to do is not have to include `hapi` when I include `scooter`, which is what is currently required. So I'd like my dependencies to be able to look like the following:

**Node module with `scooter` in it**
* `scooter`
* other modules

**Hapi Servers**
* private module with scooter and other common things in it
  * `scooter`
* `hapi`
* other modules

The problem for me is that I'll be shipping multiple versions of `hapi` each time I shrinkwrap as the module with `scooter` in it will have a version of `hapi` and each Hapi server will also have a version of `hapi` in it, which I'd like to avoid. The cause of this is the requirement of `hapi` in `peerDependencies`, which I understand the purpose of that, but I question if it is the correct solution. I do understand that currently it appears to be the only solution for `npm`.

I hope that makes it more clear, if not let me know @Marsup and I'll try to clarify the remaining parts as best as I can.

**Comment by danielb2** [comment]
@Marsup  I notice that several core libraries (h2o2, boom etc) do not have peerDependencies anymore. Is this really needed?

**Comment by Marsup** [comment]
boom is not a plugin, h2o2 is more surprising, it's probably better to still have it, as a form of documentation.

**Comment by Marsup** [comment]
To answer to @DavidTPate, I see your problem, I didn't think npm was doing that, there are several issues about it on their repo, but I don't see any valid fix we could do.

**Comment by DavidTPate** [comment]
Yeah, we haven't been able to find a valid way to handle this for ourselves either. What we ended up doing is being really permissive with our module and having `hapi >=8.x.x` in there and then relying on the flattening of dependencies that `npm>=3` does to reduce the duplicates in our `node_modules` directory. It still stinks for `shrinkwrap` but there still isn't a great way to do it as you mentioned.
