### ISSUE TITLE
Assertion error: name is missing with hapi 17 and v4.0

### ISSUE THREAD

**Issue by microcipcip** [hapijs/scooter#38]
Hi, hope this is not a stupid error from my end....I get the following error when I try to start the server:
```
{ AssertionError [ERR_ASSERTION]: Invalid plugin options {
  "plugin": {
    "register": (server, options, next) => {\n\n    server.ext('onRequest', internals.onRequest);\n    return next();\n},
    "name" [1]: -- missing --
  }
}

[1] "name" is required
```

I am registering the plugin with `await server.register(Scooter)`

**Comment by danielb2** [comment]
I published 5.x and updated the read me that you should be using 5.x

please try and let me know.

**Comment by microcipcip** [comment]
@danielb2 Thanks for the quick response. Now it is working very well :)

**Comment by bhatanku1** [comment]
Hi, I am also facing this issue. Could you please let me know what you mean by 5.x? 

Regards
Ankur

**Comment by akash9920** [comment]
Hey @microcipcip I am using inert v4.2 and facing the same issue as mentioned above. can you tell what could be the reason?
I am using hapi 17.

**Comment by Marsup** [comment]
You should start by using a compatible inert version, which for 17 would be 5+.
