### ISSUE TITLE
Minor version upgrade is a breaking change

### ISSUE THREAD

**Issue by jmaslin** [hapijs/scooter#40]
The recent update `4.0.1` added a dependency for Hapi `>=17.7.0` and updated the plugin format.

This is a breaking change for projects that are not on Hapi `17` yet because the changes are not backwards compatible.

**Comment by Marsup** [comment]
It seems the 4.0 release was wrong, the breaking change should have happened there. It is not tagged in the git tree and I can't find a commit matching what I see in the tgz. What happened there @danielb2 ?

**Comment by danielb2** [comment]
I updated peer dependencies using the format we've been using: https://github.com/hapijs/scooter/pull/37

Did I miss plugin requirements with that release?

The 4.0.1 release has requirements for 17.7  ( https://github.com/hapijs/scooter/issues/39 )

**Comment by Marsup** [comment]
Well, now you point at #37, the last comment on it also mentions there's something wrong with it. 4.0.0 is a 3.something, just look at the content of the tgz.

**Comment by danielb2** [comment]
Hm. I'm not sure what happened and it's been 2+ years since the release. How about a 4.0.2 release to fix the issue @jmaslin  is seeing now, and a 5.0 release for the breaking change ?

**Comment by Marsup** [comment]
@hueniverse are you using that 4.0.1 somewhere? We could unpublish 4.0.1 and roll out a 5.0 indeed.

**Comment by hueniverse** [comment]
I don't use this plugin.

**Comment by danielb2** [comment]
@Marsup  OK, then we can unpublish 4.0.1 after publishing this one

**Comment by danielb2** [comment]
@marsup

**Comment by Marsup** [comment]
What are you expecting from me?

**Comment by hueniverse** [comment]
@danielb2 you are the lead maintainer. What help do you need to resolve this?

**Comment by danielb2** [comment]
Sorry for the delay.  Since it's not possible to unpublish (only deprecate), @jmaslin  should use 4.0.0 unless he is on hapi 17.   The other option is to email support@npmjs.com and ask them to unpublish 4.0.1

The reason there was a discrepancy of the latest version was because somehow I had published a version 5.0.0 already. It's not clear why it's not in github or why it didn't get published there. 

As such, for the changes made in 4.0.1, those should be in 5.0.1

**Comment by danielb2** [comment]
see https://github.com/hapijs/scooter/pull/43

**Comment by Marsup** [comment]
You can always depreciate 4.0.1 and publish a 4.0.2 that's identical to 4.0.0.

**Comment by danielb2** [comment]
done
